"""initial schema

Revision ID: 999e7248e7bc
Revises:
Create Date: 2026-08-05 15:55:21.052723
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "999e7248e7bc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="queued", nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("force", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counters", sa.JSON(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','partial_success','success','failed','interrupted')",
            name=op.f("ck_llm_runs_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_runs")),
    )
    with op.batch_alter_table("llm_runs", schema=None) as batch_op:
        batch_op.create_index("ix_llm_runs_created_at", ["created_at"], unique=False)

    op.create_table(
        "profile_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "criteria_status", sa.String(length=20), server_default="missing", nullable=False
        ),
        sa.Column("criteria", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "criteria_status IN ('missing','pending','ready','failed')",
            name=op.f("ck_profile_versions_valid_criteria_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_versions")),
        sa.UniqueConstraint("profile_hash", name=op.f("uq_profile_versions_profile_hash")),
    )
    op.create_table(
        "properties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("street_address", sa.String(length=300), nullable=False),
        sa.Column("unit_number", sa.String(length=100), nullable=True),
        sa.Column("municipality", sa.String(length=150), nullable=False),
        sa.Column("state", sa.String(length=2), server_default="MA", nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("parcel_id", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("state = 'MA'", name=op.f("ck_properties_massachusetts_only")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
    )
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.create_index("ix_properties_municipality", ["municipality"], unique=False)
        batch_op.create_index("ix_properties_parcel", ["municipality", "parcel_id"], unique=False)

    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="queued", nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counters", sa.JSON(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','partial_success','success','failed','interrupted')",
            name=op.f("ck_scan_jobs_valid_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_jobs")),
    )
    with op.batch_alter_table("scan_jobs", schema=None) as batch_op:
        batch_op.create_index("ix_scan_jobs_created_at", ["created_at"], unique=False)

    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_listing_id", sa.String(length=200), nullable=False),
        sa.Column("episode_key", sa.String(length=200), server_default="initial", nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_listings_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint(
            "source", "source_listing_id", "episode_key", name="uq_listing_source_episode"
        ),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_listings_property_source", ["property_id", "source"], unique=False
        )

    op.create_table(
        "llm_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("llm_run_id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("profile_hash", sa.String(length=64), nullable=False),
        sa.Column("property_data_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column("structured_result", sa.JSON(), nullable=True),
        sa.Column("evaluation_text", sa.Text(), nullable=True),
        sa.Column("missing_information", sa.JSON(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','success','failed')",
            name=op.f("ck_llm_evaluations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["llm_run_id"],
            ["llm_runs.id"],
            name=op.f("fk_llm_evaluations_llm_run_id_llm_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_hash"],
            ["profile_versions.profile_hash"],
            name=op.f("fk_llm_evaluations_profile_hash_profile_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_llm_evaluations_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_evaluations")),
    )
    with op.batch_alter_table("llm_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_llm_evaluation_cache",
            [
                "property_id",
                "profile_hash",
                "property_data_hash",
                "provider",
                "model",
                "prompt_version",
            ],
            unique=False,
        )
        batch_op.create_index(
            "ix_llm_evaluation_current", ["property_id", "is_current"], unique=False
        )

    op.create_table(
        "property_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("normalized_value", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Integer(), server_default="100", nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100",
            name=op.f("ck_property_aliases_confidence_percentage"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_property_aliases_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_aliases")),
        sa.UniqueConstraint("kind", "normalized_value", name="uq_property_alias_identity"),
    )
    with op.batch_alter_table("property_aliases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_property_aliases_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "scan_source_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_job_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="queued", nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counters", sa.JSON(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','success','failed','blocked','skipped')",
            name=op.f("ck_scan_source_runs_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.id"],
            name=op.f("fk_scan_source_runs_scan_job_id_scan_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_source_runs")),
        sa.UniqueConstraint("scan_job_id", "source", name="uq_scan_source_run"),
    )
    op.create_table(
        "sold_comparables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_property_id", sa.Integer(), nullable=False),
        sa.Column("sold_property_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_record_id", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=True),
        sa.Column("sale_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("original_listing_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("final_listing_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("distance_miles", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("similarity", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sale_price IS NULL OR sale_price >= 0",
            name=op.f("ck_sold_comparables_nonnegative_sale_price"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_property_id"],
            ["properties.id"],
            name=op.f("fk_sold_comparables_candidate_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sold_property_id"],
            ["properties.id"],
            name=op.f("fk_sold_comparables_sold_property_id_properties"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sold_comparables")),
        sa.UniqueConstraint(
            "candidate_property_id",
            "source",
            "source_record_id",
            name="uq_candidate_source_comparable",
        ),
    )
    with op.batch_alter_table("sold_comparables", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sold_comparables_candidate_property_id"),
            ["candidate_property_id"],
            unique=False,
        )

    op.create_table(
        "listing_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("bedrooms", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("bathrooms", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("living_area_sqft", sa.Integer(), nullable=True),
        sa.Column("property_tax_annual", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("hoa_monthly", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price IS NULL OR price >= 0", name=op.f("ck_listing_states_nonnegative_price")
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_states_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_states")),
        sa.UniqueConstraint("listing_id", "content_hash", name="uq_listing_state_content"),
    )
    with op.batch_alter_table("listing_states", schema=None) as batch_op:
        batch_op.create_index(
            "ix_listing_states_listing_created", ["listing_id", "created_at"], unique=False
        )

    op.create_table(
        "property_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("event_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_property_events_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("fk_property_events_property_id_properties"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_events")),
        sa.UniqueConstraint("event_fingerprint", name="uq_property_event_fingerprint"),
    )
    with op.batch_alter_table("property_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_property_events_property_occurred", ["property_id", "occurred_at"], unique=False
        )

    op.create_table(
        "scan_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_job_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("listing_state_id", sa.Integer(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_scan_observations_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["listing_state_id"],
            ["listing_states.id"],
            name=op.f("fk_scan_observations_listing_state_id_listing_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.id"],
            name=op.f("fk_scan_observations_scan_job_id_scan_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_observations")),
        sa.UniqueConstraint("scan_job_id", "listing_id", name="uq_scan_listing_observation"),
    )
    with op.batch_alter_table("scan_observations", schema=None) as batch_op:
        batch_op.create_index("ix_scan_observations_state", ["listing_state_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_observations", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_observations_state")

    op.drop_table("scan_observations")
    with op.batch_alter_table("property_events", schema=None) as batch_op:
        batch_op.drop_index("ix_property_events_property_occurred")

    op.drop_table("property_events")
    with op.batch_alter_table("listing_states", schema=None) as batch_op:
        batch_op.drop_index("ix_listing_states_listing_created")

    op.drop_table("listing_states")
    with op.batch_alter_table("sold_comparables", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sold_comparables_candidate_property_id"))

    op.drop_table("sold_comparables")
    op.drop_table("scan_source_runs")
    with op.batch_alter_table("property_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_property_aliases_property_id"))

    op.drop_table("property_aliases")
    with op.batch_alter_table("llm_evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_evaluation_current")
        batch_op.drop_index("ix_llm_evaluation_cache")

    op.drop_table("llm_evaluations")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index("ix_listings_property_source")

    op.drop_table("listings")
    with op.batch_alter_table("scan_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_jobs_created_at")

    op.drop_table("scan_jobs")
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.drop_index("ix_properties_parcel")
        batch_op.drop_index("ix_properties_municipality")

    op.drop_table("properties")
    op.drop_table("profile_versions")
    with op.batch_alter_table("llm_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_runs_created_at")

    op.drop_table("llm_runs")
    # ### end Alembic commands ###
